language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: benBzXCN1JhJ349tA1wpmtKx7gDQ8AZbYT9odAXSy1zc1ZbDRfNICyRMJiJIbiBV7IUPmazFejbDgiU3fD8twPF9HdtZrQgbv+TrX3So6RIueE3mJ+fMnQCRkDJnp8mdNELd0yltUZrxroXdb6o+oX+e1HvkH3acBR17e0PuJik=
mQm
  app: flasktaskr_project
  on:
    branch: master
    python: '3.4'
    repo: mperham2/flasktaskr_project
